import type { ResumeData } from "@/types/resume";

/**
 * Centralized AI prompt templates for consistent and effective AI interactions
 */

/**
 * Shared humanization directive for natural, human-like AI outputs
 */
const HUMANIZATION_DIRECTIVE = `
WRITING STYLE REQUIREMENTS (CRITICAL - Follow these precisely):
- Write as an experienced professional would—natural, confident, and authoritative
- Vary sentence structure and length for a smooth, engaging reading rhythm
- Avoid robotic AI patterns: Don't overuse words like "leverage", "utilize", "synergize", "optimize"
- Use strong, specific language—be direct and impactful, not vague or generic
- Sound like a trusted career coach or senior recruiter giving personalized advice
- Match the tone to context: professional for resumes, approachable for suggestions
- Every sentence should feel like it was crafted by an expert, not generated by a machine
- Avoid starting consecutive sentences the same way
- Use contractions naturally where appropriate (e.g., "you'll" instead of "you will")
- Be concise—eliminate filler words and redundant phrases`;


export function buildResumeAnalysisPrompt(resumeData: ResumeData): string {
  return `You are an expert resume reviewer and career coach. Analyze the following resume and provide detailed, actionable feedback.
${HUMANIZATION_DIRECTIVE}

RESUME DATA:
${JSON.stringify(resumeData, null, 2)}

Please provide your analysis in the following JSON format:
{
  "overallScore": <number 0-100>,
  "strengths": [<list of 3-5 key strengths>],
  "weaknesses": [<list of 3-5 areas needing improvement>],
  "skillGaps": [<list of in-demand skills the candidate should consider adding>],
  "suggestions": [
    {
      "section": "<section name>",
      "suggestion": "<specific actionable suggestion>",
      "priority": "<high|medium|low>"
    }
  ]
}

Focus on:
1. ATS (Applicant Tracking System) compatibility
2. Impact and achievements vs. responsibilities
3. Quantifiable results and metrics
4. Keyword optimization for the candidate's field
5. Overall clarity and conciseness
6. Professional formatting and structure

Be specific, constructive, and actionable in your feedback.`;
}

export function buildContentRewritePrompt(
  text: string,
  tone: string,
  length: "short" | "medium" | "long" = "medium"
): string {
  const toneInstructions: Record<string, string> = {
    professional:
      "Rewrite this to sound more professional and polished while maintaining the same core information. Use action verbs and industry-standard terminology. Ensure the tone is confident but not arrogant.",
    confident:
      "Rewrite this to sound confident and authoritative. Highlight achievements and impact strongly.",
    friendly:
      "Rewrite this to be approachable and friendly while maintaining professionalism.",
    // Legacy support
    concise:
      "Rewrite this to be concise and impactful. Remove redundancy and focus on the most important points.",
    detailed:
      "Expand this text with more context. Add specific examples/elaboration while maintaining clarity.",
  };
  
  const lengthInstructions = {
    short: "Keep it short and concise (approx. 30-50 words or 1-2 sentences). Focus only on the most critical information.",
    medium: "Keep it moderate in length (approx. 50-100 words or 3-4 sentences). Balance detail with readability.",
    long: "Provide a detailed explanation (approx. 100+ words or 5+ sentences). Include comprehensive context and examples."
  };

  return `${toneInstructions[tone] || toneInstructions["professional"]}
  
LENGTH REQUIREMENT: ${lengthInstructions[length]}
${HUMANIZATION_DIRECTIVE}

ORIGINAL TEXT:
${text}

REQUIREMENTS:
- Maintain factual accuracy
- Keep the same general meaning
- Use active voice
- Ensure ATS-friendly language
- Return ONLY the rewritten text, no explanations or meta-commentary

REWRITTEN TEXT:`;
}

export function buildSummarizePrompt(text: string, context?: string): string {
  const contextNote = context ? `\n\nContext: ${context}` : "";

  return `Summarize the following text into a clear, concise summary. Focus on the most important information and key takeaways.${contextNote}
${HUMANIZATION_DIRECTIVE}

TEXT TO SUMMARIZE:
${text}

REQUIREMENTS:
- Be concise but comprehensive
- Capture key points and main ideas
- Use professional language
- Return ONLY the summary, no meta-commentary

SUMMARY:`;
}

export function buildLinkedInAnalysisPrompt(profileText: string): string {
  return `You are a LinkedIn optimization expert and recruiter. Analyze the following LinkedIn profile and provide detailed recommendations for improvement.
${HUMANIZATION_DIRECTIVE}

LINKEDIN PROFILE:
${profileText}

Please provide your analysis in the following JSON format:
{
  "profileScore": <number 0-100>,
  "headlineSuggestions": [<3-5 improved headline options>],
  "summarySuggestions": [<2-3 key improvements for the About/Summary section>],
  "keywordOptimization": {
    "missing": [<important keywords missing from the profile>],
    "recommended": [<strategic keywords to add based on industry/role>]
  },
  "recruiterReadiness": {
    "score": <number 0-100>,
    "improvementAreas": [<specific areas to improve for recruiter visibility>]
  },
  "actionableRecommendations": [
    {
      "category": "<Headline|Summary|Experience|Skills|etc>",
      "recommendation": "<specific action to take>",
      "impact": "<high|medium|low>"
    }
  ]
}

Focus on:
1. Headline optimization for search visibility
2. About section compelling storytelling
3. Keyword density for recruiter searches
4. Profile completeness and professional branding
5. Achievement highlighting and metrics
6. Industry-specific best practices

Be specific, data-driven, and actionable.`;
}

export function buildImproveSectionPrompt(
  sectionName: string,
  content: string,
  resumeContext?: Partial<ResumeData>
): string {
  const contextNote = resumeContext
    ? `\n\nCONTEXT (Full Resume):\n${JSON.stringify(resumeContext, null, 2)}`
    : "";

  return `You are an expert resume writer. Improve the following "${sectionName}" section of a resume. Make it more impactful, ATS-friendly, and compelling to hiring managers.
${HUMANIZATION_DIRECTIVE}

CURRENT CONTENT:
${content}${contextNote}

REQUIREMENTS:
- Use strong action verbs
- Quantify achievements where possible
- Focus on impact and results, not just responsibilities
- Ensure ATS keyword optimization
- Keep it concise yet comprehensive
- Maintain professional tone
- Return ONLY the improved content, no explanations

IMPROVED CONTENT:`;
}

export function buildGenerateFromJobTitlePrompt(
  jobTitle: string,
  company?: string
): string {
  const companyNote = company ? ` at ${company}` : "";

  return `Generate a professional, impactful job description for a "${jobTitle}" position${companyNote}. 
${HUMANIZATION_DIRECTIVE} 

REQUIREMENTS:
- Write 3-5 bullet points
- Use strong action verbs (Led, Developed, Implemented, etc.)
- Focus on achievements and impact, not just responsibilities
- Include metrics and quantifiable results where typical
- Make it ATS-friendly with relevant keywords
- Keep each point concise (1-2 lines max)
- Return ONLY the bullet points, no other text

BULLET POINTS:`;
}

/**
 * Build a prompt for optimizing a resume for a specific job description
 * Uses the DCI (Dynamic Contextual Intelligence) approach
 */
export function buildJobDescriptionOptimizationPrompt(
  resumeData: import("@/types/resume").ResumeData,
  jobDescription: import("@/types/ai").JobDescriptionInput
): string {
  const lengthInstruction = jobDescription.length 
    ? `\nOPTIMIZATION LENGTH: Target a ${jobDescription.length} length for rewritten sections. ${
        jobDescription.length === 'short' ? "Be very concise and to the point." : 
        jobDescription.length === 'long' ? "Provide detailed, comprehensive descriptions." : 
        "Balance detail with conciseness."
      }`
    : "";

  return `You are an expert resume optimizer, ATS specialist, and career coach. Your task is to optimize a resume for a specific job description.
${HUMANIZATION_DIRECTIVE}
${lengthInstruction}

CRITICAL RULES - YOU MUST FOLLOW THESE:
1. NEVER fabricate, invent, or add experiences, skills, or achievements that don't exist in the original resume
2. Only enhance, rephrase, and reorganize EXISTING content to better match the job
3. Inject relevant keywords NATURALLY into existing content
4. Improve ATS compatibility while maintaining readability
5. Highlight transferable skills that ARE present in the resume
6. Quantify achievements ONLY where numbers already exist in the original

JOB DETAILS:
Title: ${jobDescription.jobTitle}
${jobDescription.company ? `Company: ${jobDescription.company}` : ""}

Job Description:
${jobDescription.description}

Required Skills:
${jobDescription.requiredSkills.join(", ")}

${jobDescription.responsibilities ? `Key Responsibilities:\n${jobDescription.responsibilities}` : ""}

CURRENT RESUME DATA:
${JSON.stringify(resumeData, null, 2)}

PROVIDE YOUR OPTIMIZATION IN THIS EXACT JSON FORMAT:
{
  "matchScore": <number 0-100 representing how well the optimized resume matches the job>,
  "sections": [
    {
      "section": "summary",
      "sectionLabel": "Professional Summary",
      "original": "<exact original text>",
      "optimized": "<optimized text with keywords naturally integrated>",
      "changes": ["Added keyword X", "Emphasized skill Y", "Improved clarity"]
    },
    {
      "section": "experience.0.description",
      "sectionLabel": "Experience: <Company Name> - <Position>",
      "original": "<exact original description>",
      "optimized": "<optimized description>",
      "changes": ["Aligned bullet points with job requirements", "Added relevant keywords"]
    }
  ],
  "keywordsAdded": ["keyword1", "keyword2", "keyword3"],
  "gapSuggestions": [
    {
      "type": "skill",
      "suggestion": "<specific skill from job description not found in resume - recommend learning>",
      "importance": "high"
    },
    {
      "type": "experience",
      "suggestion": "<type of experience that would strengthen candidacy>",
      "importance": "medium"
    }
  ]
}

SECTIONS TO OPTIMIZE (in order of priority):
1. personalInfo.summary - Rewrite the professional summary to align with the job
2. experience[].description - Optimize each job description's bullet points
3. skills - Note which skills to highlight (but don't add fake ones)
4. projects[].description - Align project descriptions if relevant

REMEMBER:
- The "original" field must contain the EXACT original text
- The "optimized" field contains your improved version
- The "changes" array explains what you changed
- Gap suggestions are for skills/experience the candidate DOESN'T have but should consider acquiring
- Keep optimizations professional and ATS-friendly
- Maintain factual accuracy at all times`;
}

